version: '3.7'
services:
  app:
    build: .
    volumes:
      - ${PWD}:/app
      - ./vendor:/usr/local/bundle
    command: ["bundle", "exec", "puma", "config.ru", "-C", "puma.rb"]
    environment:
      - REDIS_URL=redis://toxi:40000/0
      - APP_ENV=development
      - TOXI_HOST=http://toxi:8474
    ports: 
      - "8080:9292"
  
  toxi:
    image: shopify/toxiproxy

  redis:
    image: redis:5.0.7